
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__usermanager_client_h__proxy__H__
#define __sdbuscpp__usermanager_client_h__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace com {
namespace example {

class UserManager_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "com.example.UserManager";

protected:
    UserManager_proxy(sdbus::IProxy& proxy)
        : m_proxy(proxy)
    {
    }

    UserManager_proxy(const UserManager_proxy&) = delete;
    UserManager_proxy& operator=(const UserManager_proxy&) = delete;
    UserManager_proxy(UserManager_proxy&&) = delete;
    UserManager_proxy& operator=(UserManager_proxy&&) = delete;

    ~UserManager_proxy() = default;

    void registerProxy()
    {
        m_proxy.uponSignal("UserAdded").onInterface(INTERFACE_NAME).call([this](const uint64_t& userId, const std::string& username){ this->onUserAdded(userId, username); });
    }

    virtual void onUserAdded(const uint64_t& userId, const std::string& username) = 0;

public:
    uint64_t AddUser(const std::string& username, const uint32_t& age, const std::string& email)
    {
        uint64_t result;
        m_proxy.callMethod("AddUser").onInterface(INTERFACE_NAME).withArguments(username, age, email).storeResultsTo(result);
        return result;
    }

    sdbus::Struct<std::string, uint32_t, std::string> GetUser(const uint64_t& userId)
    {
        sdbus::Struct<std::string, uint32_t, std::string> result;
        m_proxy.callMethod("GetUser").onInterface(INTERFACE_NAME).withArguments(userId).storeResultsTo(result);
        return result;
    }

    std::map<uint64_t, sdbus::Struct<std::string, uint32_t, std::string>> GetAllUsers()
    {
        std::map<uint64_t, sdbus::Struct<std::string, uint32_t, std::string>> result;
        m_proxy.callMethod("GetAllUsers").onInterface(INTERFACE_NAME).storeResultsTo(result);
        return result;
    }

    void UpdateUserTags(const uint64_t& userId, const std::vector<sdbus::Variant>& tags)
    {
        m_proxy.callMethod("UpdateUserTags").onInterface(INTERFACE_NAME).withArguments(userId, tags);
    }

public:
    uint32_t UserCount()
    {
        return m_proxy.getProperty("UserCount").onInterface(INTERFACE_NAME).get<uint32_t>();
    }

    std::map<std::string, sdbus::Variant> Config()
    {
        return m_proxy.getProperty("Config").onInterface(INTERFACE_NAME).get<std::map<std::string, sdbus::Variant>>();
    }

    void Config(const std::map<std::string, sdbus::Variant>& value)
    {
        m_proxy.setProperty("Config").onInterface(INTERFACE_NAME).toValue(value);
    }

private:
    sdbus::IProxy& m_proxy;
};

}} // namespaces

#endif
