
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__usermanager_server_h__adaptor__H__
#define __sdbuscpp__usermanager_server_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace com {
namespace example {

class UserManager_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "com.example.UserManager";

protected:
    UserManager_adaptor(sdbus::IObject& object)
        : m_object(object)
    {
    }

    UserManager_adaptor(const UserManager_adaptor&) = delete;
    UserManager_adaptor& operator=(const UserManager_adaptor&) = delete;
    UserManager_adaptor(UserManager_adaptor&&) = delete;
    UserManager_adaptor& operator=(UserManager_adaptor&&) = delete;

    ~UserManager_adaptor() = default;

    void registerAdaptor()
    {
        m_object.addVTable( sdbus::registerMethod("AddUser").withInputParamNames("username", "age", "email").withOutputParamNames("userId").implementedAs([this](const std::string& username, const uint32_t& age, const std::string& email){ return this->AddUser(username, age, email); })
                          , sdbus::registerMethod("GetUser").withInputParamNames("userId").withOutputParamNames("userInfo").implementedAs([this](const uint64_t& userId){ return this->GetUser(userId); })
                          , sdbus::registerMethod("GetAllUsers").withOutputParamNames("users").implementedAs([this](){ return this->GetAllUsers(); })
                          , sdbus::registerMethod("UpdateUserTags").withInputParamNames("userId", "tags").implementedAs([this](const uint64_t& userId, const std::vector<sdbus::Variant>& tags){ return this->UpdateUserTags(userId, tags); })
                          , sdbus::registerSignal("UserAdded").withParameters<uint64_t, std::string>("userId", "username")
                          , sdbus::registerProperty("UserCount").withGetter([this](){ return this->UserCount(); })
                          , sdbus::registerProperty("Config").withGetter([this](){ return this->Config(); }).withSetter([this](const std::map<std::string, sdbus::Variant>& value){ this->Config(value); }).withUpdateBehavior(sdbus::Flags::EMITS_CHANGE_SIGNAL)
                          ).forInterface(INTERFACE_NAME);
    }

public:
    void emitUserAdded(const uint64_t& userId, const std::string& username)
    {
        m_object.emitSignal("UserAdded").onInterface(INTERFACE_NAME).withArguments(userId, username);
    }

private:
    virtual uint64_t AddUser(const std::string& username, const uint32_t& age, const std::string& email) = 0;
    virtual sdbus::Struct<std::string, uint32_t, std::string> GetUser(const uint64_t& userId) = 0;
    virtual std::map<uint64_t, sdbus::Struct<std::string, uint32_t, std::string>> GetAllUsers() = 0;
    virtual void UpdateUserTags(const uint64_t& userId, const std::vector<sdbus::Variant>& tags) = 0;

private:
    virtual uint32_t UserCount() = 0;
    virtual std::map<std::string, sdbus::Variant> Config() = 0;
    virtual void Config(const std::map<std::string, sdbus::Variant>& value) = 0;

private:
    sdbus::IObject& m_object;
};

}} // namespaces

#endif
